### PR TITLE
Add Persistent::Vector[1,2,3] for creation

### PR DESCRIPTION
**Pull request by plexus**
I would in general like to propose that custom data structure implementations add a Klass[] method for creation, this is in line with what Ruby itself does, and provides a uniform creation interface so implementations can be swapped more easily

``` ruby
Array[1,2,3]
Hash[:foo => :bar]
Set[3,3,4]
Matrix[[1,2,3],[4,5,6]]
```

### CODE REVIEW

**Comment by Who828** [comment]
I also added a new method to create vector (like Array.new) which I felt might be a common way as well. I removed the old .vector I had for creation since that one didn't make sense any more.

**Comment by plexus** [comment]
:+1:

**Comment by plexus** [comment]
Did you also copy the semantics of Array.new? It can be a bit surprising if you're not used to them

``` ruby
Array.new(5) #=> [nil, nil, nil, nil, nil]
Array.new(3, :x) #=> [:x, :x, :x]
```

**Comment by Who828** [comment]
Ah, I haven't.   I guess I will revert the change for now and later implement a new method which behaves like Array.new

**Comment by plexus** [comment]
That would make sense, although I feel less strongly about copying that. I for one rarely use that. But might be worth discussing at https://github.com/plexus/rubydataspec/issues if we want that to be part of the "spec".

**Pull request merged**
